
package ma.ensa.client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CountriesPort", targetNamespace = "http://www.ensa.ma/MySoapService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountriesPort {


    /**
     * 
     * @param getAllCountriesRequest
     * @return
     *     returns ma.ensa.client.GetAllCountriesResponse
     */
    @WebMethod
    @WebResult(name = "getAllCountriesResponse", targetNamespace = "http://www.ensa.ma/MySoapService", partName = "getAllCountriesResponse")
    public GetAllCountriesResponse getAllCountries(
        @WebParam(name = "getAllCountriesRequest", targetNamespace = "http://www.ensa.ma/MySoapService", partName = "getAllCountriesRequest")
        GetAllCountriesRequest getAllCountriesRequest);

    /**
     * 
     * @param getCountryRequest
     * @return
     *     returns ma.ensa.client.GetCountryResponse
     */
    @WebMethod
    @WebResult(name = "getCountryResponse", targetNamespace = "http://www.ensa.ma/MySoapService", partName = "getCountryResponse")
    public GetCountryResponse getCountry(
        @WebParam(name = "getCountryRequest", targetNamespace = "http://www.ensa.ma/MySoapService", partName = "getCountryRequest")
        GetCountryRequest getCountryRequest);

    /**
     * 
     * @param addCountryRequest
     * @return
     *     returns ma.ensa.client.AddCountryResponse
     */
    @WebMethod
    @WebResult(name = "addCountryResponse", targetNamespace = "http://www.ensa.ma/MySoapService", partName = "addCountryResponse")
    public AddCountryResponse addCountry(
        @WebParam(name = "addCountryRequest", targetNamespace = "http://www.ensa.ma/MySoapService", partName = "addCountryRequest")
        AddCountryRequest addCountryRequest);

    /**
     * 
     * @param updateCountryRequest
     * @return
     *     returns ma.ensa.client.UpdateCountryResponse
     */
    @WebMethod
    @WebResult(name = "updateCountryResponse", targetNamespace = "http://www.ensa.ma/MySoapService", partName = "updateCountryResponse")
    public UpdateCountryResponse updateCountry(
        @WebParam(name = "updateCountryRequest", targetNamespace = "http://www.ensa.ma/MySoapService", partName = "updateCountryRequest")
        UpdateCountryRequest updateCountryRequest);

    /**
     * 
     * @param deleteCountryRequest
     * @return
     *     returns ma.ensa.client.DeleteCountryResponse
     */
    @WebMethod
    @WebResult(name = "deleteCountryResponse", targetNamespace = "http://www.ensa.ma/MySoapService", partName = "deleteCountryResponse")
    public DeleteCountryResponse deleteCountry(
        @WebParam(name = "deleteCountryRequest", targetNamespace = "http://www.ensa.ma/MySoapService", partName = "deleteCountryRequest")
        DeleteCountryRequest deleteCountryRequest);

}
